Paynless/paynless

- package.json
- src/components/history/index.js
- src/components/index.js
2 Features:
- Refactored to use Browser Router instead of Hash Router.
- Protected Home page from non-authorized users.
> Login required

- src/components/protected/Dashboard.js
- src/components/protected/tab.js
> deleted console logs and console logs

- src/components/customer/OpenTabs.js
*Added Features:*
- Added a loading state to open tabs
- Added an empty state to open tabs
> feature: Open Tabs has a loading state and an empty state

- src/components/customer/OpenTabs.js
- src/helpers/utilities.js
Refactored open tabs to simplify logic of setting state
Refactored open tabs to user fireview withAuth component
> Chore: Open tabs refactor

- src/components/admin/adminHome.js
- src/components/admin/adminTab.js
- src/components/admin/index.js
- src/components/customer/BottomBar.js
- src/components/customer/OpenTabs.js
- src/components/index.js
*Feature:*
- As an admin, I can view open tabs for the merchant associated with my account
*Testing Notes:*
- Login with admin@example.com to test
- Go to /admin
> Feature: Admin View Tabs

- functions/index.js
- functions/package-lock.json
- functions/package.json
- cd into /functions folder and npm install
- should be able to register new users and it will automatically create a stripe account/association for them
> feat: add stripe integration, basic account creation

- src/components/admin/adminSingleTab.js
- src/components/admin/adminTab.js
- src/components/admin/index.js
- src/components/admin/menuItem.js
- src/components/customer/Tab.js
- src/components/index.js
- src/index.css
*Feature:*
- Admins can add any menu items to the tab
> Feature: Ability to add items to a tab

- src/helpers/auth.js
- Fixes duplicate user creation on login
> fix: remove duplicate users on state change

- src/components/auth/Register.js
- src/components/customer/BottomBar.js
- src/components/customer/CheckIn.js
- src/components/customer/Favorite.js
- src/components/customer/Logo.js
- src/components/customer/SelectMerchant.js
- src/components/customer/index.js
- src/components/customer/splashScreen.js
- src/components/index.js
- src/index.css
- src/index.js
*Summary:*
Users can now star their favorite watering holes! Favorited bars and restaurants will show up on the home screen for easy access.
*Details:*
- Added a favorite object to the user model. NOTE: breaking change for new users, all users will need an empty favorites object on them when created in the future
- Redid the search for bars component to include a new FE component that allows toggling what items are their favorite and what are not. It also displays favorites when the search field is blank.
> Feature: Favorites

- .env
- package.json
- public/index.html
- public/manifest.json
- src/components/customer/CheckIn.js
- src/components/customer/SelectMerchant.js
- src/components/index.js
- src/components/main/Menu.js
- src/components/main/Routes.js
- src/components/merchants/AddVenue.js
- src/components/merchants/index.js
- src/helpers/auth.js
- src/helpers/index.js
- src/helpers/locationAPIs.js
- src/helpers/utilities.js
- Business page added. We can now add merchants from the front end
- Users, Tabs, and Merchants will ALL have id's upon creation in firebase!
> add 'add business' page and enhace utility functions

- src/components/customer/CardSection.js
- src/components/main/App.js
- src/components/main/Menu.js
- src/components/main/Routes.js
- src/helpers/auth.js
Summary: The App component now listens to changes in the user object. 
Details:
- Upon completion of withAuth, user listener is created and user object is added to the state
- User obj is passed to all necessary components as a prop
- Menu: admin panel button is hidden if user is not admin
- Routes: AdminRoute created, unauthorized users meet with angry message
- CardSection: minor changes in anticipation of user edits
> feat: add userObj as prop to all components

- functions/index.js
- package.json
- src/components/customer/CardSection.js
- src/components/customer/CheckIn.js
- src/components/customer/Checkout.js
- src/components/customer/CreditCardDropdown.js
- src/components/customer/SelectMerchant.js
- src/components/customer/Tab.js
- Charges the customer once they click pay
- Prelim without UI
> feat: charge the customer on checkout

- functions/index.js
- src/components/customer/CardSection.js
- src/components/customer/Checkout.js
- src/components/customer/CreateTab.js
- src/components/customer/SelectMerchant.js
- src/components/main/App.js
- src/helpers/auth.js
- src/helpers/utilities.js
Summary: uid of users is always the doc id. changes in auth, app, create tab, and select merchant for accomodation
> make doc id equal uid

- package.json
- src/components/customer/CardSection.js
- src/helpers/auth.js
- Fixes persisting google auth
- Removes duplication of users
- Merges googleAuth with email
- uid same for both
> Google auth fix

- functions/index.js
- src/components/customer/CardSection.js
- src/components/customer/Checkout.js
- src/components/customer/CustomerInfo.js
- src/components/customer/InfoForm.js
- Update firebase functions to use "Users" collection
> chore: re-deploy cloud functions

- functions/index.js
- src/components/customer/CardSection.js
- src/components/customer/Checkout.js
- Update db.collection query to "Users"
> fix: update query path

- functions/index.js
> fix: add slash to path

- functions/index.js
- src/components/admin/adminHome.js
- src/components/admin/adminSingleTab.js
- src/components/customer/Checkout.js
- src/components/customer/OpenTabs.js
- src/components/customer/Tab.js
- src/index.css
*Features:*
- Ability to checkout while charging actual money
- Ability to cancel checkout without charging money
- Error handling if checkout goes wrong with stripe
- Ability to just close empty tabs without charging anything
*Fixes:*
- Fixed bug where admin side was not working
> Feature: Ability to checkout

- src/components/auth/Register.js
- src/components/customer/CreateTab.js
- src/helpers/utilities.js
Summary: Dialog is pops up if no payment methods are detected. 
Details:
- User can either click dialog button and redirect to payment details, or click outside of dialog and browse the remainder of the app.
> Payment Method Check

- package.json
- src/components/auth/Login.js
- src/index.css
Refactored the login with google button to use a raised button of the same style as login.
Added a svg with a transparent background
> Fix: refactored login with google button to match rest of application styles

- src/components/customer/OpenTabs.js
- src/components/customer/TabHistory.js
- src/components/customer/index.js
- src/components/main/Menu.js
- src/components/main/Routes.js
- src/helpers/utilities.js
Summary: History page will render all previously closed tabs.
Details:
- Tab History Component
- Open Tab refractor
- Related Routes/Menu alterations
> feat: add tab history component, refactor open tabs to match tab history

- src/components/customer/CardSection.js
Fix: added a few lines to remove the listener when we leave the component
> Fix: Bug where toggling favorites after adding card causes the app to crash

- src/components/customer/CardSection.js
Fix: fixed error on older android phones where they can still submit invalid cards. Added error handling and messaging
> Fix: Users on older android can submit invalid cards

- src/components/customer/Profile.js
- src/components/customer/index.js
- src/components/index.js
- src/components/main/Routes.js
- src/helpers/auth.js
- src/index.css
> feat: add profile ui

- firebase.json
added configuration to firebase to configure it as a single page application
> Config: Configured firebase to be a single page application

- src/components/admin/AdminSingleTab.js
- src/components/customer/CreateTab.js
Summary: Find near me is now light green. Dropdown is below Create Tab Button
> Style: change button colors

- src/components/main/Menu.js
- src/index.css
*Feature:*
- Header uses the user avatar component.
> Feature: Menu Header uses User Avatar

- src/index.css
Changed the CSS to make sure container is at least as wide as all elements.
> Fix: small fix to fix overlap problem at wide screen widths.
